// -------------------------------------------------------------
// 
// File Name: hdlsrc_v\DUCforLTEHDL\CIC_Compensation_Interpolator.v
// Created: 2023-02-09 10:49:26
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: CIC_Compensation_Interpolator
// Source Path: DUCforLTEHDL/HDL_DUC/CIC Compensation Interpolator
// Hierarchy Level: 1
// 
// HDLFIRInterpolation
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module CIC_Compensation_Interpolator
          (clk,
           reset,
           enb,
           dataIn,
           validIn,
           dataOut,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [17:0] dataIn;  // sfix18_En14
  input   validIn;
  output  signed [17:0] dataOut;  // sfix18_En14
  output  validOut;


  wire syncReset;
  wire signed [17:0] FIROutput1;  // sfix18_En14
  wire FIRValid1;
  wire outputSharingRSTTerm2;
  wire sharingReset;
  wire counterRST;
  wire validSharing;
  reg  sharingSEL_1;  // ufix1
  wire SharingSEL0;
  wire SharingCount0;
  wire outputSharingRSTTerm1;
  wire outputSharingRSTTerm3;
  reg  outputSharing_1;
  wire counterEnTerm;
  wire counterEn;
  reg [1:0] sharingCounter_1;  // ufix2
  wire validOutTerm;
  reg  validOut_1;
  wire signed [17:0] dataZero;  // sfix18_En14
  reg  sharingSELREG;  // ufix1
  reg signed [17:0] FIROutputCastDB1;  // sfix18_En14
  wire signed [17:0] FIROutput2;  // sfix18_En14
  wire FIRValid2;
  reg signed [17:0] FIROutputCastDB2;  // sfix18_En14
  wire signed [17:0] dataSelect;  // sfix18_En14


  assign syncReset = 1'b0;



  FIRFilter1 u_filterInstantiation (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .dataIn(dataIn),  // sfix18_En14
                                    .validIn(validIn),
                                    .dataOut(FIROutput1),  // sfix18_En14
                                    .validOut(FIRValid1)
                                    );

  assign outputSharingRSTTerm2 =  ~ FIRValid1;



  assign counterRST =  ~ sharingReset;



  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 1
  always @(posedge clk or posedge reset)
    begin : SharingSEL_process
      if (reset == 1'b1) begin
        sharingSEL_1 <= 1'b0;
      end
      else begin
        if (enb && validSharing) begin
          sharingSEL_1 <=  ~ sharingSEL_1;
        end
      end
    end



  assign SharingSEL0 = sharingSEL_1 == 1'b0;



  assign outputSharingRSTTerm1 = SharingCount0 & SharingSEL0;



  assign outputSharingRSTTerm3 = outputSharingRSTTerm1 & outputSharingRSTTerm2;



  assign sharingReset = syncReset | outputSharingRSTTerm3;



  always @(posedge clk or posedge reset)
    begin : OutputSharing_process
      if (reset == 1'b1) begin
        outputSharing_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (sharingReset == 1'b1) begin
            outputSharing_1 <= 1'b0;
          end
          else begin
            if (FIRValid1) begin
              outputSharing_1 <= FIRValid1;
            end
          end
        end
      end
    end



  assign counterEnTerm = outputSharing_1 | FIRValid1;



  assign counterEn = counterEnTerm & counterRST;



  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 1
  always @(posedge clk or posedge reset)
    begin : SharingCounter_process
      if (reset == 1'b1) begin
        sharingCounter_1 <= 2'b00;
      end
      else begin
        if (enb) begin
          if (counterEn == 1'b1) begin
            if (sharingCounter_1 >= 2'b01) begin
              sharingCounter_1 <= 2'b00;
            end
            else begin
              sharingCounter_1 <= sharingCounter_1 + 2'b01;
            end
          end
        end
      end
    end



  assign SharingCount0 = sharingCounter_1 == 2'b00;



  assign validSharing = SharingCount0 & counterEn;



  assign validOutTerm = validSharing | FIRValid1;



  always @(posedge clk or posedge reset)
    begin : OutputSharing_2_process
      if (reset == 1'b1) begin
        validOut_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            validOut_1 <= 1'b0;
          end
          else begin
            validOut_1 <= validOutTerm;
          end
        end
      end
    end



  assign dataZero = 18'sb000000000000000000;



  always @(posedge clk or posedge reset)
    begin : OutputSharing_3_process
      if (reset == 1'b1) begin
        sharingSELREG <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            sharingSELREG <= 1'b0;
          end
          else begin
            if (validSharing) begin
              sharingSELREG <= sharingSEL_1;
            end
          end
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        FIROutputCastDB1 <= 18'sb000000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            FIROutputCastDB1 <= 18'sb000000000000000000;
          end
          else begin
            if (FIRValid1) begin
              FIROutputCastDB1 <= FIROutput1;
            end
          end
        end
      end
    end



  FIRFilter2 u_filterInstantiation_1 (.clk(clk),
                                      .reset(reset),
                                      .enb(enb),
                                      .dataIn(dataIn),  // sfix18_En14
                                      .validIn(validIn),
                                      .dataOut(FIROutput2),  // sfix18_En14
                                      .validOut(FIRValid2)
                                      );

  always @(posedge clk or posedge reset)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        FIROutputCastDB2 <= 18'sb000000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            FIROutputCastDB2 <= 18'sb000000000000000000;
          end
          else begin
            if (FIRValid2) begin
              FIROutputCastDB2 <= FIROutput2;
            end
          end
        end
      end
    end



  assign dataSelect = (sharingSELREG == 1'b0 ? FIROutputCastDB1 :
              FIROutputCastDB2);



  assign dataOut = (validOut_1 == 1'b0 ? dataZero :
              dataSelect);



  assign validOut = validOut_1;

endmodule  // CIC_Compensation_Interpolator

