// -------------------------------------------------------------
// 
// File Name: hdlsrc_v\DUCforLTEHDL\DUCforLTEHDL.v
// Created: 2023-02-09 10:48:25
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 4.88281e-07
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: DUCforLTEHDL
// Source Path: DUCforLTEHDL
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module DUCforLTEHDL;




  // Implementation of a Digital Up-Converter for UWC
  // Uncomment the dcuIn block instead of Const to have Input Baseband Sine 
  // Change the FC in the M-file to change the output frequency 


endmodule  // DUCforLTEHDL

