// -------------------------------------------------------------
// 
// File Name: hdlsrc_v\DUCforLTEHDL\FIRFilter1_block1.v
// Created: 2023-02-09 10:49:26
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FIRFilter1_block1
// Source Path: DUCforLTEHDL/HDL_DUC/Lowpass Interpolator/DUCforLTEHDL/HDL_DUC/Lowpass Interpolator/FIRFilter1
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FIRFilter1_block1
          (clk,
           reset,
           enb,
           dataIn,
           validIn,
           dataOut,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] dataIn;  // sfix16_En15
  input   validIn;
  output  signed [17:0] dataOut;  // sfix18_En14
  output  validOut;


  wire signed [15:0] dinSM;  // sfix16_En15
  wire dinVldSM;
  reg [3:0] nextDelayLineRdAddrReverse;  // ufix4
  reg [3:0] rdCountReverse_1;  // ufix4
  reg [3:0] nextDelayLineWrAddr;  // ufix4
  reg [3:0] wrCount_1;  // ufix4
  reg [3:0] nextDelayLineRdAddr;  // ufix4
  reg [3:0] rdCount_1;  // ufix4
  reg [3:0] nextSharingCount;  // ufix4
  reg [3:0] sharingCount_1;  // ufix4
  reg  delayLineValidInP;
  reg  lastPhaseStrobe;
  reg  delayLineShiftEnP;
  reg  delayLineShiftEn1_1;
  wire syncResetRst;
  reg  delayLineShiftEn2_1;
  reg  delayLineShiftEn3_1;
  reg  delayLineShiftEn4_1;
  reg  delayLineShiftEn5_1;
  reg  [0:6] validOutLookahead_reg;  // ufix1 [7]
  wire [0:6] validOutLookahead_reg_next;  // ufix1 [7]
  wire validOutLookahead_1;
  reg  vldOut_1;
  wire notValid;
  reg [3:0] rdAddr0_1;  // ufix4
  reg [3:0] rdAddr1;  // ufix4
  reg [3:0] rdAddr2;  // ufix4
  reg [3:0] rdAddr3;  // ufix4
  reg [3:0] rdAddr4;  // ufix4
  reg [3:0] rdAddr5;  // ufix4
  wire rdAddrEndNonZero;
  wire rdAddrEndZero;
  reg  [0:5] finalSumValidPipe_reg;  // ufix1 [6]
  wire [0:5] finalSumValidPipe_reg_next;  // ufix1 [6]
  wire accumulate;
  wire signed [32:0] accDataOut;  // sfix33_En30
  reg [3:0] wrAddrP;  // ufix4
  reg [3:0] rdAddrDelayLine0;  // ufix4
  wire signed [15:0] delayLineEnd0;  // sfix16_En15
  wire signed [15:0] delayLineDataOut0;  // sfix16_En15
  reg signed [15:0] delayLineDataIn1_1;  // sfix16_En15
  reg [3:0] wrAddr1;  // ufix4
  reg [3:0] rdAddrDelayLine1;  // ufix4
  wire signed [15:0] delayLineEnd1;  // sfix16_En15
  wire signed [15:0] delayLineDataOut1;  // sfix16_En15
  reg signed [15:0] delayLineDataIn2_1;  // sfix16_En15
  reg [3:0] wrAddr2;  // ufix4
  reg [3:0] rdAddrDelayLine2;  // ufix4
  wire signed [15:0] delayLineEnd2;  // sfix16_En15
  wire signed [15:0] delayLineDataOut2;  // sfix16_En15
  reg signed [15:0] delayLineDataIn3_1;  // sfix16_En15
  reg [3:0] wrAddr3;  // ufix4
  reg [3:0] rdAddrDelayLine3;  // ufix4
  wire signed [15:0] delayLineEnd3;  // sfix16_En15
  wire signed [15:0] delayLineDataOut3;  // sfix16_En15
  reg signed [15:0] delayLineDataIn4_1;  // sfix16_En15
  reg [3:0] wrAddr4;  // ufix4
  reg [3:0] rdAddrDelayLine4;  // ufix4
  wire signed [15:0] delayLineEnd4;  // sfix16_En15
  wire signed [15:0] delayLineDataOut4;  // sfix16_En15
  reg signed [15:0] delayLineDataIn5_1;  // sfix16_En15
  wire signed [15:0] delayLineEnd5;  // sfix16_En15
  wire signed [15:0] delayLineDataOut5;  // sfix16_En15
  reg signed [15:0] coeffTableOut4;  // sfix16_En15
  reg signed [15:0] coeffTableRegP4_1;  // sfix16_En15
  reg signed [15:0] coeffTableReg4_1;  // sfix16_En15
  reg [3:0] rdAddReverse1;  // ufix4
  reg [3:0] rdAddReverse2;  // ufix4
  reg [3:0] rdAddReverse3;  // ufix4
  reg [3:0] rdAddReverse4;  // ufix4
  wire signed [15:0] delayLineEnd6;  // sfix16_En15
  wire signed [15:0] delayLineDataOut6;  // sfix16_En15
  reg signed [15:0] coeffTableOut3;  // sfix16_En15
  reg signed [15:0] coeffTableRegP3_1;  // sfix16_En15
  reg signed [15:0] coeffTableReg3_1;  // sfix16_En15
  wire signed [15:0] delayLineEnd7;  // sfix16_En15
  wire signed [15:0] delayLineDataOut7;  // sfix16_En15
  reg signed [15:0] coeffTableOut2;  // sfix16_En15
  reg signed [15:0] coeffTableRegP2_1;  // sfix16_En15
  reg signed [15:0] coeffTableReg2_1;  // sfix16_En15
  wire signed [15:0] delayLineEnd8;  // sfix16_En15
  wire signed [15:0] delayLineDataOut8;  // sfix16_En15
  reg signed [15:0] coeffTableOut1;  // sfix16_En15
  reg signed [15:0] coeffTableRegP1_1;  // sfix16_En15
  reg signed [15:0] coeffTableReg1_1;  // sfix16_En15
  wire signed [15:0] delayLineEnd9deadOut;  // sfix16_En15
  wire signed [15:0] delayLineDataOut9;  // sfix16_En15
  reg signed [15:0] coeffTableOut0;  // sfix16_En15
  reg signed [15:0] coeffTableRegP0_1;  // sfix16_En15
  reg signed [15:0] coeffTableReg0_1;  // sfix16_En15
  wire signed [32:0] sumIn;  // sfix33_En30
  wire signed [32:0] sumOut;  // sfix33_En30
  wire signed [32:0] sumOut_0;  // sfix33_En30
  wire signed [32:0] sumOut_1;  // sfix33_En30
  wire signed [32:0] sumOut_2;  // sfix33_En30
  wire signed [32:0] sumOut_3;  // sfix33_En30
  reg signed [32:0] sumOutReg_1;  // sfix33_En30
  reg signed [32:0] accDataOut_1;  // sfix33_En30
  wire signed [32:0] accSwitchOut;  // sfix33_En30
  wire signed [32:0] accAdderOut;  // sfix33_En30
  wire signed [17:0] converterOut;  // sfix18_En14
  reg signed [17:0] dout_re_1;  // sfix18_En14
  wire signed [17:0] dataZero;  // sfix18_En14
  reg [3:0] InputControl_out4_0;  // ufix4

  initial begin
    coeffTableRegP4_1 = 16'sb0000000000000000;
    coeffTableRegP3_1 = 16'sb0000000000000000;
    coeffTableRegP2_1 = 16'sb0000000000000000;
    coeffTableRegP1_1 = 16'sb0000000000000000;
    coeffTableRegP0_1 = 16'sb0000000000000000;
  end

  FirRdyLogic_block3 u_firRdyLogic (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .dataIn(dataIn),  // sfix16_En15
                                    .validIn(validIn),
                                    .dinSM(dinSM),  // sfix16_En15
                                    .dinVldSM(dinVldSM)
                                    );

  always @(posedge clk or posedge reset)
    begin : rdCountReverse_process
      if (reset == 1'b1) begin
        rdCountReverse_1 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdCountReverse_1 <= nextDelayLineRdAddrReverse;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : wrCount_process
      if (reset == 1'b1) begin
        wrCount_1 <= 4'b0000;
      end
      else begin
        if (enb) begin
          wrCount_1 <= nextDelayLineWrAddr;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdCount_process
      if (reset == 1'b1) begin
        rdCount_1 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdCount_1 <= nextDelayLineRdAddr;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : sharingCount_process
      if (reset == 1'b1) begin
        sharingCount_1 <= 4'b0000;
      end
      else begin
        if (enb) begin
          sharingCount_1 <= nextSharingCount;
        end
      end
    end



  // Input control counter combinatorial logic
  always @(dinVldSM, rdCountReverse_1, rdCount_1, sharingCount_1, wrCount_1) begin
    delayLineValidInP = (sharingCount_1 == 4'b0000) && (dinVldSM == 1'b1);
    lastPhaseStrobe = sharingCount_1 == 4'b1110;
    if ((dinVldSM == 1'b1) || (sharingCount_1 > 4'b0000)) begin
      if (sharingCount_1 == 4'b1111) begin
        nextSharingCount = 4'b0000;
      end
      else begin
        nextSharingCount = sharingCount_1 + 4'b0001;
      end
    end
    else begin
      nextSharingCount = sharingCount_1;
    end
    if (dinVldSM == 1'b1) begin
      if (wrCount_1 == 4'b1110) begin
        InputControl_out4_0 = 4'b0000;
      end
      else begin
        InputControl_out4_0 = wrCount_1 + 4'b0001;
      end
    end
    else begin
      InputControl_out4_0 = wrCount_1;
    end
    if ((rdCount_1 != InputControl_out4_0) || (dinVldSM == 1'b1)) begin
      if (rdCount_1 == 4'b0000) begin
        nextDelayLineRdAddr = 4'b1110;
      end
      else begin
        nextDelayLineRdAddr = rdCount_1 - 4'b0001;
      end
    end
    else begin
      nextDelayLineRdAddr = rdCount_1;
    end
    if ((sharingCount_1 > 4'b0000) || (dinVldSM == 1'b1)) begin
      if (sharingCount_1 == 4'b1111) begin
        if (wrCount_1 == 4'b1110) begin
          nextDelayLineRdAddrReverse = 4'b0000;
        end
        else begin
          nextDelayLineRdAddrReverse = wrCount_1 + 4'b0001;
        end
      end
      else if (rdCountReverse_1 == 4'b1110) begin
        nextDelayLineRdAddrReverse = 4'b0000;
      end
      else begin
        nextDelayLineRdAddrReverse = rdCountReverse_1 + 4'b0001;
      end
    end
    else begin
      nextDelayLineRdAddrReverse = rdCountReverse_1;
    end
    nextDelayLineWrAddr = InputControl_out4_0;
  end



  always @(posedge clk or posedge reset)
    begin : delayLineShiftEn0_process
      if (reset == 1'b1) begin
        delayLineShiftEnP <= 1'b0;
      end
      else begin
        if (enb) begin
          delayLineShiftEnP <= lastPhaseStrobe;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : delayLineShiftEn1_process
      if (reset == 1'b1) begin
        delayLineShiftEn1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          delayLineShiftEn1_1 <= delayLineShiftEnP;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : delayLineShiftEn2_process
      if (reset == 1'b1) begin
        delayLineShiftEn2_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncResetRst == 1'b1) begin
            delayLineShiftEn2_1 <= 1'b0;
          end
          else begin
            delayLineShiftEn2_1 <= delayLineShiftEn1_1;
          end
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : delayLineShiftEn3_process
      if (reset == 1'b1) begin
        delayLineShiftEn3_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncResetRst == 1'b1) begin
            delayLineShiftEn3_1 <= 1'b0;
          end
          else begin
            delayLineShiftEn3_1 <= delayLineShiftEn2_1;
          end
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : delayLineShiftEn4_process
      if (reset == 1'b1) begin
        delayLineShiftEn4_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncResetRst == 1'b1) begin
            delayLineShiftEn4_1 <= 1'b0;
          end
          else begin
            delayLineShiftEn4_1 <= delayLineShiftEn3_1;
          end
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : delayLineShiftEn5_process
      if (reset == 1'b1) begin
        delayLineShiftEn5_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncResetRst == 1'b1) begin
            delayLineShiftEn5_1 <= 1'b0;
          end
          else begin
            delayLineShiftEn5_1 <= delayLineShiftEn4_1;
          end
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : validOutLookahead_process
      if (reset == 1'b1) begin
        validOutLookahead_reg[0] <= 1'b0;
        validOutLookahead_reg[1] <= 1'b0;
        validOutLookahead_reg[2] <= 1'b0;
        validOutLookahead_reg[3] <= 1'b0;
        validOutLookahead_reg[4] <= 1'b0;
        validOutLookahead_reg[5] <= 1'b0;
        validOutLookahead_reg[6] <= 1'b0;
      end
      else begin
        if (enb) begin
          validOutLookahead_reg[0] <= validOutLookahead_reg_next[0];
          validOutLookahead_reg[1] <= validOutLookahead_reg_next[1];
          validOutLookahead_reg[2] <= validOutLookahead_reg_next[2];
          validOutLookahead_reg[3] <= validOutLookahead_reg_next[3];
          validOutLookahead_reg[4] <= validOutLookahead_reg_next[4];
          validOutLookahead_reg[5] <= validOutLookahead_reg_next[5];
          validOutLookahead_reg[6] <= validOutLookahead_reg_next[6];
        end
      end
    end

  assign validOutLookahead_1 = validOutLookahead_reg[6];
  assign validOutLookahead_reg_next[0] = delayLineShiftEn5_1;
  assign validOutLookahead_reg_next[1] = validOutLookahead_reg[0];
  assign validOutLookahead_reg_next[2] = validOutLookahead_reg[1];
  assign validOutLookahead_reg_next[3] = validOutLookahead_reg[2];
  assign validOutLookahead_reg_next[4] = validOutLookahead_reg[3];
  assign validOutLookahead_reg_next[5] = validOutLookahead_reg[4];
  assign validOutLookahead_reg_next[6] = validOutLookahead_reg[5];



  always @(posedge clk or posedge reset)
    begin : vldOut_process
      if (reset == 1'b1) begin
        vldOut_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          vldOut_1 <= validOutLookahead_1;
        end
      end
    end



  assign notValid =  ~ vldOut_1;



  always @(posedge clk or posedge reset)
    begin : rdAddr0_process
      if (reset == 1'b1) begin
        rdAddr0_1 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdAddr0_1 <= sharingCount_1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddr0_2_process
      if (reset == 1'b1) begin
        rdAddr1 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdAddr1 <= rdAddr0_1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddr1_1_process
      if (reset == 1'b1) begin
        rdAddr2 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdAddr2 <= rdAddr1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddr2_1_process
      if (reset == 1'b1) begin
        rdAddr3 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdAddr3 <= rdAddr2;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddr3_1_process
      if (reset == 1'b1) begin
        rdAddr4 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdAddr4 <= rdAddr3;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddr4_1_process
      if (reset == 1'b1) begin
        rdAddr5 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdAddr5 <= rdAddr4;
        end
      end
    end



  assign rdAddrEndNonZero = rdAddr5 != 4'b0000;



  assign rdAddrEndZero =  ~ rdAddrEndNonZero;



  always @(posedge clk or posedge reset)
    begin : finalSumValidPipe_process
      if (reset == 1'b1) begin
        finalSumValidPipe_reg[0] <= 1'b0;
        finalSumValidPipe_reg[1] <= 1'b0;
        finalSumValidPipe_reg[2] <= 1'b0;
        finalSumValidPipe_reg[3] <= 1'b0;
        finalSumValidPipe_reg[4] <= 1'b0;
        finalSumValidPipe_reg[5] <= 1'b0;
      end
      else begin
        if (enb) begin
          finalSumValidPipe_reg[0] <= finalSumValidPipe_reg_next[0];
          finalSumValidPipe_reg[1] <= finalSumValidPipe_reg_next[1];
          finalSumValidPipe_reg[2] <= finalSumValidPipe_reg_next[2];
          finalSumValidPipe_reg[3] <= finalSumValidPipe_reg_next[3];
          finalSumValidPipe_reg[4] <= finalSumValidPipe_reg_next[4];
          finalSumValidPipe_reg[5] <= finalSumValidPipe_reg_next[5];
        end
      end
    end

  assign accumulate = finalSumValidPipe_reg[5];
  assign finalSumValidPipe_reg_next[0] = rdAddrEndZero;
  assign finalSumValidPipe_reg_next[1] = finalSumValidPipe_reg[0];
  assign finalSumValidPipe_reg_next[2] = finalSumValidPipe_reg[1];
  assign finalSumValidPipe_reg_next[3] = finalSumValidPipe_reg[2];
  assign finalSumValidPipe_reg_next[4] = finalSumValidPipe_reg[3];
  assign finalSumValidPipe_reg_next[5] = finalSumValidPipe_reg[4];



  assign accDataOut = 33'sh000000000;



  always @(posedge clk or posedge reset)
    begin : wrAddr_process
      if (reset == 1'b1) begin
        wrAddrP <= 4'b0000;
      end
      else begin
        if (enb) begin
          wrAddrP <= wrCount_1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddrDelayLine_process
      if (reset == 1'b1) begin
        rdAddrDelayLine0 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine0 <= rdCount_1;
        end
      end
    end



  Addressable_Delay_Line_block4 u_delayLine0 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .dataIn(dinSM),  // sfix16_En15
                                              .wrEn(delayLineValidInP),
                                              .wrAddr(wrAddrP),  // ufix4
                                              .rdAddr(rdAddrDelayLine0),  // ufix4
                                              .delayLineEnd(delayLineEnd0),  // sfix16_En15
                                              .dataOut(delayLineDataOut0)  // sfix16_En15
                                              );

  always @(posedge clk or posedge reset)
    begin : delayLineDataIn1_process
      if (reset == 1'b1) begin
        delayLineDataIn1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn1_1 <= delayLineEnd0;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : wrAddr0_process
      if (reset == 1'b1) begin
        wrAddr1 <= 4'b0000;
      end
      else begin
        if (enb) begin
          wrAddr1 <= wrAddrP;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddrDelayLine0_1_process
      if (reset == 1'b1) begin
        rdAddrDelayLine1 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine1 <= rdAddrDelayLine0;
        end
      end
    end



  Addressable_Delay_Line_block4 u_delayLine1 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .dataIn(delayLineDataIn1_1),  // sfix16_En15
                                              .wrEn(delayLineShiftEn1_1),
                                              .wrAddr(wrAddr1),  // ufix4
                                              .rdAddr(rdAddrDelayLine1),  // ufix4
                                              .delayLineEnd(delayLineEnd1),  // sfix16_En15
                                              .dataOut(delayLineDataOut1)  // sfix16_En15
                                              );

  always @(posedge clk or posedge reset)
    begin : delayLineDataIn2_process
      if (reset == 1'b1) begin
        delayLineDataIn2_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn2_1 <= delayLineEnd1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : wrAddr1_1_process
      if (reset == 1'b1) begin
        wrAddr2 <= 4'b0000;
      end
      else begin
        if (enb) begin
          wrAddr2 <= wrAddr1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddrDelayLine1_1_process
      if (reset == 1'b1) begin
        rdAddrDelayLine2 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine2 <= rdAddrDelayLine1;
        end
      end
    end



  Addressable_Delay_Line_block4 u_delayLine2 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .dataIn(delayLineDataIn2_1),  // sfix16_En15
                                              .wrEn(delayLineShiftEn2_1),
                                              .wrAddr(wrAddr2),  // ufix4
                                              .rdAddr(rdAddrDelayLine2),  // ufix4
                                              .delayLineEnd(delayLineEnd2),  // sfix16_En15
                                              .dataOut(delayLineDataOut2)  // sfix16_En15
                                              );

  always @(posedge clk or posedge reset)
    begin : delayLineDataIn3_process
      if (reset == 1'b1) begin
        delayLineDataIn3_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn3_1 <= delayLineEnd2;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : wrAddr2_1_process
      if (reset == 1'b1) begin
        wrAddr3 <= 4'b0000;
      end
      else begin
        if (enb) begin
          wrAddr3 <= wrAddr2;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddrDelayLine2_1_process
      if (reset == 1'b1) begin
        rdAddrDelayLine3 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine3 <= rdAddrDelayLine2;
        end
      end
    end



  Addressable_Delay_Line_block4 u_delayLine3 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .dataIn(delayLineDataIn3_1),  // sfix16_En15
                                              .wrEn(delayLineShiftEn3_1),
                                              .wrAddr(wrAddr3),  // ufix4
                                              .rdAddr(rdAddrDelayLine3),  // ufix4
                                              .delayLineEnd(delayLineEnd3),  // sfix16_En15
                                              .dataOut(delayLineDataOut3)  // sfix16_En15
                                              );

  always @(posedge clk or posedge reset)
    begin : delayLineDataIn4_process
      if (reset == 1'b1) begin
        delayLineDataIn4_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn4_1 <= delayLineEnd3;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : wrAddr3_1_process
      if (reset == 1'b1) begin
        wrAddr4 <= 4'b0000;
      end
      else begin
        if (enb) begin
          wrAddr4 <= wrAddr3;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddrDelayLine3_1_process
      if (reset == 1'b1) begin
        rdAddrDelayLine4 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine4 <= rdAddrDelayLine3;
        end
      end
    end



  Addressable_Delay_Line_block5 u_delayLine4 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .dataIn(delayLineDataIn4_1),  // sfix16_En15
                                              .wrEn(delayLineShiftEn4_1),
                                              .wrAddr(wrAddr4),  // ufix4
                                              .rdAddr(rdAddrDelayLine4),  // ufix4
                                              .lutAddr(rdAddr4),  // ufix4
                                              .delayLineEnd(delayLineEnd4),  // sfix16_En15
                                              .dataOut(delayLineDataOut4)  // sfix16_En15
                                              );

  always @(posedge clk or posedge reset)
    begin : delayLineDataIn5_process
      if (reset == 1'b1) begin
        delayLineDataIn5_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn5_1 <= delayLineEnd4;
        end
      end
    end



  Addressable_Delay_Line_block6 u_delayLine5 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .dataIn(delayLineDataIn5_1),  // sfix16_En15
                                              .validIn(delayLineShiftEn5_1),
                                              .lutaddr(rdAddr5),  // ufix4
                                              .delayLineEnd(delayLineEnd5),  // sfix16_En15
                                              .dataOut(delayLineDataOut5)  // sfix16_En15
                                              );

  // Coefficient table for multiplier4
  always @(rdAddr4) begin
    case ( rdAddr4)
      4'b0000 :
        begin
          coeffTableOut4 = 16'sb0000001011010100;
        end
      4'b0001 :
        begin
          coeffTableOut4 = 16'sb1111110010101101;
        end
      4'b0010 :
        begin
          coeffTableOut4 = 16'sb0000001111101100;
        end
      4'b0011 :
        begin
          coeffTableOut4 = 16'sb1111101101011000;
        end
      4'b0100 :
        begin
          coeffTableOut4 = 16'sb0000010110010111;
        end
      4'b0101 :
        begin
          coeffTableOut4 = 16'sb1111100100101100;
        end
      4'b0110 :
        begin
          coeffTableOut4 = 16'sb0000100010010100;
        end
      4'b0111 :
        begin
          coeffTableOut4 = 16'sb1111010010111011;
        end
      4'b1000 :
        begin
          coeffTableOut4 = 16'sb0001000000001000;
        end
      4'b1001 :
        begin
          coeffTableOut4 = 16'sb1110010100000000;
        end
      4'b1010 :
        begin
          coeffTableOut4 = 16'sb0101000101101111;
        end
      4'b1011 :
        begin
          coeffTableOut4 = 16'sb0000000000000000;
        end
      4'b1100 :
        begin
          coeffTableOut4 = 16'sb0000000000000000;
        end
      4'b1101 :
        begin
          coeffTableOut4 = 16'sb0000000000000000;
        end
      4'b1110 :
        begin
          coeffTableOut4 = 16'sb0000000000000000;
        end
      default :
        begin
          coeffTableOut4 = 16'sb0000000000000000;
        end
    endcase
  end



  always @(posedge clk)
    begin : coeffTableRegP4_process
      if (enb) begin
        coeffTableRegP4_1 <= coeffTableOut4;
      end
    end



  always @(posedge clk or posedge reset)
    begin : coeffTableReg4_process
      if (reset == 1'b1) begin
        coeffTableReg4_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg4_1 <= coeffTableRegP4_1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddrReverse0_process
      if (reset == 1'b1) begin
        rdAddReverse1 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdAddReverse1 <= rdCountReverse_1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddReverse1_1_process
      if (reset == 1'b1) begin
        rdAddReverse2 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdAddReverse2 <= rdAddReverse1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddReverse2_1_process
      if (reset == 1'b1) begin
        rdAddReverse3 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdAddReverse3 <= rdAddReverse2;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddReverse3_1_process
      if (reset == 1'b1) begin
        rdAddReverse4 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdAddReverse4 <= rdAddReverse3;
        end
      end
    end



  Addressable_Delay_Line_block7 u_delayLine6 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .dataIn(delayLineEnd5),  // sfix16_En15
                                              .validIn(delayLineShiftEn4_1),
                                              .wrAddr(wrAddr4),  // ufix4
                                              .rdAddr(rdAddReverse4),  // ufix4
                                              .delayLineEnd(delayLineEnd6),  // sfix16_En15
                                              .dataOut(delayLineDataOut6)  // sfix16_En15
                                              );

  // Coefficient table for multiplier3
  always @(rdAddr3) begin
    case ( rdAddr3)
      4'b0000 :
        begin
          coeffTableOut3 = 16'sb0000000000110101;
        end
      4'b0001 :
        begin
          coeffTableOut3 = 16'sb1111111111100000;
        end
      4'b0010 :
        begin
          coeffTableOut3 = 16'sb0000000000001001;
        end
      4'b0011 :
        begin
          coeffTableOut3 = 16'sb0000000000010001;
        end
      4'b0100 :
        begin
          coeffTableOut3 = 16'sb1111111111010010;
        end
      4'b0101 :
        begin
          coeffTableOut3 = 16'sb0000000001001110;
        end
      4'b0110 :
        begin
          coeffTableOut3 = 16'sb1111111110001101;
        end
      4'b0111 :
        begin
          coeffTableOut3 = 16'sb0000000010011011;
        end
      4'b1000 :
        begin
          coeffTableOut3 = 16'sb1111111100110111;
        end
      4'b1001 :
        begin
          coeffTableOut3 = 16'sb0000000011111011;
        end
      4'b1010 :
        begin
          coeffTableOut3 = 16'sb1111111011001100;
        end
      4'b1011 :
        begin
          coeffTableOut3 = 16'sb0000000101110011;
        end
      4'b1100 :
        begin
          coeffTableOut3 = 16'sb1111111001000110;
        end
      4'b1101 :
        begin
          coeffTableOut3 = 16'sb0000001000001011;
        end
      4'b1110 :
        begin
          coeffTableOut3 = 16'sb1111110110010111;
        end
      default :
        begin
          coeffTableOut3 = 16'sb0000000000000000;
        end
    endcase
  end



  always @(posedge clk)
    begin : coeffTableRegP3_process
      if (enb) begin
        coeffTableRegP3_1 <= coeffTableOut3;
      end
    end



  always @(posedge clk or posedge reset)
    begin : coeffTableReg3_process
      if (reset == 1'b1) begin
        coeffTableReg3_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg3_1 <= coeffTableRegP3_1;
        end
      end
    end



  Addressable_Delay_Line_block7 u_delayLine7 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .dataIn(delayLineEnd6),  // sfix16_En15
                                              .validIn(delayLineShiftEn3_1),
                                              .wrAddr(wrAddr3),  // ufix4
                                              .rdAddr(rdAddReverse3),  // ufix4
                                              .delayLineEnd(delayLineEnd7),  // sfix16_En15
                                              .dataOut(delayLineDataOut7)  // sfix16_En15
                                              );

  // Coefficient table for multiplier2
  always @(rdAddr2) begin
    case ( rdAddr2)
      4'b0000 :
        begin
          coeffTableOut2 = 16'sb1111111101111100;
        end
      4'b0001 :
        begin
          coeffTableOut2 = 16'sb0000000010000111;
        end
      4'b0010 :
        begin
          coeffTableOut2 = 16'sb1111111101110110;
        end
      4'b0011 :
        begin
          coeffTableOut2 = 16'sb0000000010001100;
        end
      4'b0100 :
        begin
          coeffTableOut2 = 16'sb1111111101110011;
        end
      4'b0101 :
        begin
          coeffTableOut2 = 16'sb0000000010001101;
        end
      4'b0110 :
        begin
          coeffTableOut2 = 16'sb1111111101110101;
        end
      4'b0111 :
        begin
          coeffTableOut2 = 16'sb0000000010001000;
        end
      4'b1000 :
        begin
          coeffTableOut2 = 16'sb1111111101111100;
        end
      4'b1001 :
        begin
          coeffTableOut2 = 16'sb0000000001111110;
        end
      4'b1010 :
        begin
          coeffTableOut2 = 16'sb1111111110001001;
        end
      4'b1011 :
        begin
          coeffTableOut2 = 16'sb0000000001101110;
        end
      4'b1100 :
        begin
          coeffTableOut2 = 16'sb1111111110011101;
        end
      4'b1101 :
        begin
          coeffTableOut2 = 16'sb0000000001010110;
        end
      4'b1110 :
        begin
          coeffTableOut2 = 16'sb1111111110111010;
        end
      default :
        begin
          coeffTableOut2 = 16'sb0000000000000000;
        end
    endcase
  end



  always @(posedge clk)
    begin : coeffTableRegP2_process
      if (enb) begin
        coeffTableRegP2_1 <= coeffTableOut2;
      end
    end



  always @(posedge clk or posedge reset)
    begin : coeffTableReg2_process
      if (reset == 1'b1) begin
        coeffTableReg2_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg2_1 <= coeffTableRegP2_1;
        end
      end
    end



  Addressable_Delay_Line_block7 u_delayLine8 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .dataIn(delayLineEnd7),  // sfix16_En15
                                              .validIn(delayLineShiftEn2_1),
                                              .wrAddr(wrAddr2),  // ufix4
                                              .rdAddr(rdAddReverse2),  // ufix4
                                              .delayLineEnd(delayLineEnd8),  // sfix16_En15
                                              .dataOut(delayLineDataOut8)  // sfix16_En15
                                              );

  // Coefficient table for multiplier1
  always @(rdAddr1) begin
    case ( rdAddr1)
      4'b0000 :
        begin
          coeffTableOut1 = 16'sb0000000000101011;
        end
      4'b0001 :
        begin
          coeffTableOut1 = 16'sb1111111111001111;
        end
      4'b0010 :
        begin
          coeffTableOut1 = 16'sb0000000000110111;
        end
      4'b0011 :
        begin
          coeffTableOut1 = 16'sb1111111111000011;
        end
      4'b0100 :
        begin
          coeffTableOut1 = 16'sb0000000001000100;
        end
      4'b0101 :
        begin
          coeffTableOut1 = 16'sb1111111110110110;
        end
      4'b0110 :
        begin
          coeffTableOut1 = 16'sb0000000001010001;
        end
      4'b0111 :
        begin
          coeffTableOut1 = 16'sb1111111110101001;
        end
      4'b1000 :
        begin
          coeffTableOut1 = 16'sb0000000001011110;
        end
      4'b1001 :
        begin
          coeffTableOut1 = 16'sb1111111110011100;
        end
      4'b1010 :
        begin
          coeffTableOut1 = 16'sb0000000001101010;
        end
      4'b1011 :
        begin
          coeffTableOut1 = 16'sb1111111110010000;
        end
      4'b1100 :
        begin
          coeffTableOut1 = 16'sb0000000001110110;
        end
      4'b1101 :
        begin
          coeffTableOut1 = 16'sb1111111110000101;
        end
      4'b1110 :
        begin
          coeffTableOut1 = 16'sb0000000010000000;
        end
      default :
        begin
          coeffTableOut1 = 16'sb0000000000000000;
        end
    endcase
  end



  always @(posedge clk)
    begin : coeffTableRegP1_process
      if (enb) begin
        coeffTableRegP1_1 <= coeffTableOut1;
      end
    end



  always @(posedge clk or posedge reset)
    begin : coeffTableReg1_process
      if (reset == 1'b1) begin
        coeffTableReg1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg1_1 <= coeffTableRegP1_1;
        end
      end
    end



  Addressable_Delay_Line_block7 u_delayLine9 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .dataIn(delayLineEnd8),  // sfix16_En15
                                              .validIn(delayLineShiftEn1_1),
                                              .wrAddr(wrAddr1),  // ufix4
                                              .rdAddr(rdAddReverse1),  // ufix4
                                              .delayLineEnd(delayLineEnd9deadOut),  // sfix16_En15
                                              .dataOut(delayLineDataOut9)  // sfix16_En15
                                              );

  // Coefficient table for multiplier0
  always @(rdAddr0_1) begin
    case ( rdAddr0_1)
      4'b0000 :
        begin
          coeffTableOut0 = 16'sb0000000000101010;
        end
      4'b0001 :
        begin
          coeffTableOut0 = 16'sb1111111110101111;
        end
      4'b0010 :
        begin
          coeffTableOut0 = 16'sb1111111111100001;
        end
      4'b0011 :
        begin
          coeffTableOut0 = 16'sb1111111111111111;
        end
      4'b0100 :
        begin
          coeffTableOut0 = 16'sb1111111111111001;
        end
      4'b0101 :
        begin
          coeffTableOut0 = 16'sb0000000000000110;
        end
      4'b0110 :
        begin
          coeffTableOut0 = 16'sb1111111111111000;
        end
      4'b0111 :
        begin
          coeffTableOut0 = 16'sb0000000000001010;
        end
      4'b1000 :
        begin
          coeffTableOut0 = 16'sb1111111111110011;
        end
      4'b1001 :
        begin
          coeffTableOut0 = 16'sb0000000000010000;
        end
      4'b1010 :
        begin
          coeffTableOut0 = 16'sb1111111111101100;
        end
      4'b1011 :
        begin
          coeffTableOut0 = 16'sb0000000000011000;
        end
      4'b1100 :
        begin
          coeffTableOut0 = 16'sb1111111111100100;
        end
      4'b1101 :
        begin
          coeffTableOut0 = 16'sb0000000000100001;
        end
      4'b1110 :
        begin
          coeffTableOut0 = 16'sb1111111111011010;
        end
      default :
        begin
          coeffTableOut0 = 16'sb0000000000000000;
        end
    endcase
  end



  always @(posedge clk)
    begin : coeffTableRegP0_process
      if (enb) begin
        coeffTableRegP0_1 <= coeffTableOut0;
      end
    end



  always @(posedge clk or posedge reset)
    begin : coeffTableReg0_process
      if (reset == 1'b1) begin
        coeffTableReg0_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg0_1 <= coeffTableRegP0_1;
        end
      end
    end



  assign sumIn = 33'sh000000000;



  FilterTapSystolicPreAdd_block u_filterTap0 (.clk(clk),
                                              .enb(enb),
                                              .din_re(delayLineDataOut0),  // sfix16_En15
                                              .preAddIn(delayLineDataOut9),  // sfix16_En15
                                              .coeff(coeffTableReg0_1),  // sfix16_En15
                                              .sumIn(sumIn),  // sfix33_En30
                                              .sumOut(sumOut)  // sfix33_En30
                                              );

  FilterTapSystolicPreAdd_block u_filterTap1 (.clk(clk),
                                              .enb(enb),
                                              .din_re(delayLineDataOut1),  // sfix16_En15
                                              .preAddIn(delayLineDataOut8),  // sfix16_En15
                                              .coeff(coeffTableReg1_1),  // sfix16_En15
                                              .sumIn(sumOut),  // sfix33_En30
                                              .sumOut(sumOut_0)  // sfix33_En30
                                              );

  FilterTapSystolicPreAdd_block u_filterTap2 (.clk(clk),
                                              .enb(enb),
                                              .din_re(delayLineDataOut2),  // sfix16_En15
                                              .preAddIn(delayLineDataOut7),  // sfix16_En15
                                              .coeff(coeffTableReg2_1),  // sfix16_En15
                                              .sumIn(sumOut_0),  // sfix33_En30
                                              .sumOut(sumOut_1)  // sfix33_En30
                                              );

  FilterTapSystolicPreAdd_block u_filterTap3 (.clk(clk),
                                              .enb(enb),
                                              .din_re(delayLineDataOut3),  // sfix16_En15
                                              .preAddIn(delayLineDataOut6),  // sfix16_En15
                                              .coeff(coeffTableReg3_1),  // sfix16_En15
                                              .sumIn(sumOut_1),  // sfix33_En30
                                              .sumOut(sumOut_2)  // sfix33_En30
                                              );

  FilterTapSystolicPreAdd_block u_filterTap4 (.clk(clk),
                                              .enb(enb),
                                              .din_re(delayLineDataOut4),  // sfix16_En15
                                              .preAddIn(delayLineDataOut5),  // sfix16_En15
                                              .coeff(coeffTableReg4_1),  // sfix16_En15
                                              .sumIn(sumOut_2),  // sfix33_En30
                                              .sumOut(sumOut_3)  // sfix33_En30
                                              );

  always @(posedge clk or posedge reset)
    begin : sumOutReg_process
      if (reset == 1'b1) begin
        sumOutReg_1 <= 33'sh000000000;
      end
      else begin
        if (enb) begin
          sumOutReg_1 <= sumOut_3;
        end
      end
    end



  assign accSwitchOut = (accumulate == 1'b0 ? accDataOut_1 :
              accDataOut);



  assign accAdderOut = accSwitchOut + sumOutReg_1;



  always @(posedge clk or posedge reset)
    begin : accDataOut_2_process
      if (reset == 1'b1) begin
        accDataOut_1 <= 33'sh000000000;
      end
      else begin
        if (enb) begin
          accDataOut_1 <= accAdderOut;
        end
      end
    end



  assign converterOut = {accDataOut_1[32], accDataOut_1[32:16]};



  always @(posedge clk or posedge reset)
    begin : dout_re_process
      if (reset == 1'b1) begin
        dout_re_1 <= 18'sb000000000000000000;
      end
      else begin
        if (enb && validOutLookahead_1) begin
          dout_re_1 <= converterOut;
        end
      end
    end



  assign dataZero = 18'sb000000000000000000;



  assign dataOut = (notValid == 1'b0 ? dout_re_1 :
              dataZero);



  assign validOut = vldOut_1;

endmodule  // FIRFilter1_block1

