// -------------------------------------------------------------
// 
// File Name: hdlsrc_v\DUCforLTEHDL\FIRFilter1_block.v
// Created: 2023-02-09 10:49:26
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FIRFilter1_block
// Source Path: DUCforLTEHDL/HDL_DUC/Halfband Interpolator/DUCforLTEHDL/HDL_DUC/Halfband Interpolator/FIRFilter1
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FIRFilter1_block
          (clk,
           reset,
           enb,
           dataIn,
           validIn,
           dataOut,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [17:0] dataIn;  // sfix18_En14
  input   validIn;
  output  signed [17:0] dataOut;  // sfix18_En14
  output  validOut;


  wire signed [17:0] dinSM;  // sfix18_En14
  wire dinVldSM;
  reg [2:0] nextDelayLineRdAddrReverse;  // ufix3
  reg [2:0] rdCountReverse_1;  // ufix3
  reg [2:0] nextDelayLineWrAddr;  // ufix3
  reg [2:0] wrCount_1;  // ufix3
  reg [2:0] nextDelayLineRdAddr;  // ufix3
  reg [2:0] rdCount_1;  // ufix3
  reg [2:0] nextSharingCount;  // ufix3
  reg [2:0] sharingCount_1;  // ufix3
  reg  delayLineValidInP;
  reg  lastPhaseStrobe;
  reg  delayLineShiftEnP;
  reg  delayLineShiftEn1_1;
  reg  [0:4] validOutLookahead_reg;  // ufix1 [5]
  wire [0:4] validOutLookahead_reg_next;  // ufix1 [5]
  wire validOutLookahead_1;
  reg  vldOut_1;
  wire notValid;
  reg [2:0] wrAddrP;  // ufix3
  reg [2:0] rdAddrDelayLine0;  // ufix3
  wire signed [17:0] delayLineEnd0;  // sfix18_En14
  wire signed [17:0] delayLineDataOut0;  // sfix18_En14
  reg signed [17:0] delayLineDataIn1_1;  // sfix18_En14
  reg [2:0] wrAddr1;  // ufix3
  reg [2:0] rdAddReverse1;  // ufix3
  wire signed [17:0] delayLineDataOut1;  // sfix18_En14
  reg [2:0] rdAddr0_1;  // ufix3
  reg signed [17:0] coeffTableOut0;  // sfix18_En17
  reg signed [17:0] coeffTableRegP0_1;  // sfix18_En17
  reg signed [17:0] coeffTableReg0_1;  // sfix18_En17
  reg [2:0] rdAddr1;  // ufix3
  wire rdAddrEndNonZero;
  wire rdAddrEndZero;
  reg  [0:3] finalSumValidPipe_reg;  // ufix1 [4]
  wire [0:3] finalSumValidPipe_reg_next;  // ufix1 [4]
  wire accumulate;
  wire signed [35:0] accDataOut;  // sfix36_En31
  wire signed [35:0] sumOut;  // sfix36_En31
  wire signed [35:0] accSwitchOut;  // sfix36_En31
  wire signed [17:0] converterOut;  // sfix18_En14
  reg signed [17:0] dout_re_1;  // sfix18_En14
  wire signed [17:0] dataZero;  // sfix18_En14
  reg [2:0] InputControl_out4_0;  // ufix3

  initial begin
    coeffTableRegP0_1 = 18'sb000000000000000000;
  end

  FirRdyLogic_block1 u_firRdyLogic (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .dataIn(dataIn),  // sfix18_En14
                                    .validIn(validIn),
                                    .dinSM(dinSM),  // sfix18_En14
                                    .dinVldSM(dinVldSM)
                                    );

  always @(posedge clk or posedge reset)
    begin : rdCountReverse_process
      if (reset == 1'b1) begin
        rdCountReverse_1 <= 3'b000;
      end
      else begin
        if (enb) begin
          rdCountReverse_1 <= nextDelayLineRdAddrReverse;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : wrCount_process
      if (reset == 1'b1) begin
        wrCount_1 <= 3'b000;
      end
      else begin
        if (enb) begin
          wrCount_1 <= nextDelayLineWrAddr;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdCount_process
      if (reset == 1'b1) begin
        rdCount_1 <= 3'b000;
      end
      else begin
        if (enb) begin
          rdCount_1 <= nextDelayLineRdAddr;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : sharingCount_process
      if (reset == 1'b1) begin
        sharingCount_1 <= 3'b000;
      end
      else begin
        if (enb) begin
          sharingCount_1 <= nextSharingCount;
        end
      end
    end



  // Input control counter combinatorial logic
  always @(dinVldSM, rdCountReverse_1, rdCount_1, sharingCount_1, wrCount_1) begin
    delayLineValidInP = (sharingCount_1 == 3'b000) && (dinVldSM == 1'b1);
    lastPhaseStrobe = sharingCount_1 == 3'b011;
    if ((dinVldSM == 1'b1) || (sharingCount_1 > 3'b000)) begin
      if (sharingCount_1 == 3'b111) begin
        nextSharingCount = 3'b000;
      end
      else begin
        nextSharingCount = sharingCount_1 + 3'b001;
      end
    end
    else begin
      nextSharingCount = sharingCount_1;
    end
    if (dinVldSM == 1'b1) begin
      if (wrCount_1 == 3'b011) begin
        InputControl_out4_0 = 3'b000;
      end
      else begin
        InputControl_out4_0 = wrCount_1 + 3'b001;
      end
    end
    else begin
      InputControl_out4_0 = wrCount_1;
    end
    if ((rdCount_1 != InputControl_out4_0) || (dinVldSM == 1'b1)) begin
      if (rdCount_1 == 3'b000) begin
        nextDelayLineRdAddr = 3'b011;
      end
      else begin
        nextDelayLineRdAddr = rdCount_1 - 3'b001;
      end
    end
    else begin
      nextDelayLineRdAddr = rdCount_1;
    end
    if ((sharingCount_1 > 3'b000) || (dinVldSM == 1'b1)) begin
      if (sharingCount_1 == 3'b111) begin
        if (wrCount_1 == 3'b011) begin
          nextDelayLineRdAddrReverse = 3'b000;
        end
        else begin
          nextDelayLineRdAddrReverse = wrCount_1 + 3'b001;
        end
      end
      else if (rdCountReverse_1 == 3'b011) begin
        nextDelayLineRdAddrReverse = 3'b000;
      end
      else begin
        nextDelayLineRdAddrReverse = rdCountReverse_1 + 3'b001;
      end
    end
    else begin
      nextDelayLineRdAddrReverse = rdCountReverse_1;
    end
    nextDelayLineWrAddr = InputControl_out4_0;
  end



  always @(posedge clk or posedge reset)
    begin : delayLineShiftEn0_process
      if (reset == 1'b1) begin
        delayLineShiftEnP <= 1'b0;
      end
      else begin
        if (enb) begin
          delayLineShiftEnP <= lastPhaseStrobe;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : delayLineShiftEn1_process
      if (reset == 1'b1) begin
        delayLineShiftEn1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          delayLineShiftEn1_1 <= delayLineShiftEnP;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : validOutLookahead_process
      if (reset == 1'b1) begin
        validOutLookahead_reg[0] <= 1'b0;
        validOutLookahead_reg[1] <= 1'b0;
        validOutLookahead_reg[2] <= 1'b0;
        validOutLookahead_reg[3] <= 1'b0;
        validOutLookahead_reg[4] <= 1'b0;
      end
      else begin
        if (enb) begin
          validOutLookahead_reg[0] <= validOutLookahead_reg_next[0];
          validOutLookahead_reg[1] <= validOutLookahead_reg_next[1];
          validOutLookahead_reg[2] <= validOutLookahead_reg_next[2];
          validOutLookahead_reg[3] <= validOutLookahead_reg_next[3];
          validOutLookahead_reg[4] <= validOutLookahead_reg_next[4];
        end
      end
    end

  assign validOutLookahead_1 = validOutLookahead_reg[4];
  assign validOutLookahead_reg_next[0] = delayLineShiftEn1_1;
  assign validOutLookahead_reg_next[1] = validOutLookahead_reg[0];
  assign validOutLookahead_reg_next[2] = validOutLookahead_reg[1];
  assign validOutLookahead_reg_next[3] = validOutLookahead_reg[2];
  assign validOutLookahead_reg_next[4] = validOutLookahead_reg[3];



  always @(posedge clk or posedge reset)
    begin : vldOut_process
      if (reset == 1'b1) begin
        vldOut_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          vldOut_1 <= validOutLookahead_1;
        end
      end
    end



  assign notValid =  ~ vldOut_1;



  always @(posedge clk or posedge reset)
    begin : wrAddr_process
      if (reset == 1'b1) begin
        wrAddrP <= 3'b000;
      end
      else begin
        if (enb) begin
          wrAddrP <= wrCount_1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddrDelayLine_process
      if (reset == 1'b1) begin
        rdAddrDelayLine0 <= 3'b000;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine0 <= rdCount_1;
        end
      end
    end



  Addressable_Delay_Line_block1 u_delayLine0 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .dataIn(dinSM),  // sfix18_En14
                                              .wrEn(delayLineValidInP),
                                              .wrAddr(wrAddrP),  // ufix3
                                              .rdAddr(rdAddrDelayLine0),  // ufix3
                                              .delayLineEnd(delayLineEnd0),  // sfix18_En14
                                              .dataOut(delayLineDataOut0)  // sfix18_En14
                                              );

  always @(posedge clk or posedge reset)
    begin : delayLineDataIn1_process
      if (reset == 1'b1) begin
        delayLineDataIn1_1 <= 18'sb000000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn1_1 <= delayLineEnd0;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : wrAddr0_process
      if (reset == 1'b1) begin
        wrAddr1 <= 3'b000;
      end
      else begin
        if (enb) begin
          wrAddr1 <= wrAddrP;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddrReverse0_process
      if (reset == 1'b1) begin
        rdAddReverse1 <= 3'b000;
      end
      else begin
        if (enb) begin
          rdAddReverse1 <= rdCountReverse_1;
        end
      end
    end



  Addressable_Delay_Line_block2 u_delayLine1 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .dataIn(delayLineDataIn1_1),  // sfix18_En14
                                              .validIn(delayLineShiftEn1_1),
                                              .wrAddr(wrAddr1),  // ufix3
                                              .rdAddr(rdAddReverse1),  // ufix3
                                              .dataOut(delayLineDataOut1)  // sfix18_En14
                                              );

  always @(posedge clk or posedge reset)
    begin : rdAddr0_process
      if (reset == 1'b1) begin
        rdAddr0_1 <= 3'b000;
      end
      else begin
        if (enb) begin
          rdAddr0_1 <= sharingCount_1;
        end
      end
    end



  // Coefficient table for multiplier0
  always @(rdAddr0_1) begin
    case ( rdAddr0_1)
      3'b000 :
        begin
          coeffTableOut0 = 18'sb111111110000101101;
        end
      3'b001 :
        begin
          coeffTableOut0 = 18'sb000001010100001111;
        end
      3'b010 :
        begin
          coeffTableOut0 = 18'sb111011010111110010;
        end
      3'b011 :
        begin
          coeffTableOut0 = 18'sb010011100010110010;
        end
      default :
        begin
          coeffTableOut0 = 18'sb000000000000000000;
        end
    endcase
  end



  always @(posedge clk)
    begin : coeffTableRegP0_process
      if (enb) begin
        coeffTableRegP0_1 <= coeffTableOut0;
      end
    end



  always @(posedge clk or posedge reset)
    begin : coeffTableReg0_process
      if (reset == 1'b1) begin
        coeffTableReg0_1 <= 18'sb000000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg0_1 <= coeffTableRegP0_1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddr0_2_process
      if (reset == 1'b1) begin
        rdAddr1 <= 3'b000;
      end
      else begin
        if (enb) begin
          rdAddr1 <= rdAddr0_1;
        end
      end
    end



  assign rdAddrEndNonZero = rdAddr1 != 3'b000;



  assign rdAddrEndZero =  ~ rdAddrEndNonZero;



  always @(posedge clk or posedge reset)
    begin : finalSumValidPipe_process
      if (reset == 1'b1) begin
        finalSumValidPipe_reg[0] <= 1'b0;
        finalSumValidPipe_reg[1] <= 1'b0;
        finalSumValidPipe_reg[2] <= 1'b0;
        finalSumValidPipe_reg[3] <= 1'b0;
      end
      else begin
        if (enb) begin
          finalSumValidPipe_reg[0] <= finalSumValidPipe_reg_next[0];
          finalSumValidPipe_reg[1] <= finalSumValidPipe_reg_next[1];
          finalSumValidPipe_reg[2] <= finalSumValidPipe_reg_next[2];
          finalSumValidPipe_reg[3] <= finalSumValidPipe_reg_next[3];
        end
      end
    end

  assign accumulate = finalSumValidPipe_reg[3];
  assign finalSumValidPipe_reg_next[0] = rdAddrEndZero;
  assign finalSumValidPipe_reg_next[1] = finalSumValidPipe_reg[0];
  assign finalSumValidPipe_reg_next[2] = finalSumValidPipe_reg[1];
  assign finalSumValidPipe_reg_next[3] = finalSumValidPipe_reg[2];



  assign accDataOut = 36'sh000000000;



  assign accSwitchOut = (accumulate == 1'b0 ? sumOut :
              accDataOut);



  FilterTapSystolicPreAdd u_filterTap0 (.clk(clk),
                                        .enb(enb),
                                        .din_re(delayLineDataOut0),  // sfix18_En14
                                        .preAddIn(delayLineDataOut1),  // sfix18_En14
                                        .coeff(coeffTableReg0_1),  // sfix18_En17
                                        .sumIn(accSwitchOut),  // sfix36_En31
                                        .sumOut(sumOut)  // sfix36_En31
                                        );

  assign converterOut = sumOut[34:17];



  always @(posedge clk or posedge reset)
    begin : dout_re_process
      if (reset == 1'b1) begin
        dout_re_1 <= 18'sb000000000000000000;
      end
      else begin
        if (enb && validOutLookahead_1) begin
          dout_re_1 <= converterOut;
        end
      end
    end



  assign dataZero = 18'sb000000000000000000;



  assign dataOut = (notValid == 1'b0 ? dout_re_1 :
              dataZero);



  assign validOut = vldOut_1;

endmodule  // FIRFilter1_block

