// -------------------------------------------------------------
// 
// File Name: hdlsrc_v\DUCforLTEHDL\Gain_Correction.v
// Created: 2023-02-09 10:49:26
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Gain_Correction
// Source Path: DUCforLTEHDL/HDL_DUC/Gain Correction
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Gain_Correction
          (dataIn,
           dataOut);


  input   signed [17:0] dataIn;  // sfix18_En12
  output  signed [17:0] dataOut;  // sfix18_En14


  wire signed [17:0] Data_Type_Conversion_out1;  // sfix18_En14

  // Divide by 4096
  // To right-shift by 12 bits, reinterpret the number to have 
  // 20 fractional bits rather than 8 fractional bits.


  assign Data_Type_Conversion_out1 = dataIn;



  assign dataOut = Data_Type_Conversion_out1;

endmodule  // Gain_Correction

