// -------------------------------------------------------------
// 
// File Name: hdlsrc_v\DUCforLTEHDL\gcSection.v
// Created: 2023-02-09 10:49:26
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: gcSection
// Source Path: DUCforLTEHDL/HDL_DUC/CICInterpolator/gcSection
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module gcSection
          (integOut_re,
           gcOut_re);


  input   signed [19:0] integOut_re;  // sfix20_En14
  output  signed [19:0] gcOut_re;  // sfix20_En14




  assign gcOut_re = integOut_re;

endmodule  // gcSection

