// -------------------------------------------------------------
// 
// File Name: hdlsrc_v\DUCforLTEHDL\HDL_DUC.v
// Created: 2023-02-09 10:49:26
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 4.88281e-07
// Target subsystem base rate: 4.88281e-07
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        4.88281e-07
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Out1_re                       ce_out        4.88281e-07
// Out1_im                       ce_out        4.88281e-07
// Out2                          ce_out        4.88281e-07
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: HDL_DUC
// Source Path: DUCforLTEHDL/HDL_DUC
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module HDL_DUC
          (clk,
           reset,
           clk_enable,
           dataIn,
           ValidIn,
           ce_out,
           Out1_re,
           Out1_im,
           Out2);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [15:0] dataIn;  // sfix16_En15
  input   ValidIn;
  output  ce_out;
  output  signed [17:0] Out1_re;  // sfix18_En16
  output  signed [17:0] Out1_im;  // sfix18_En16
  output  Out2;


  wire enb;
  wire signed [17:0] LP;  // sfix18_En14
  wire LP_Valid;
  wire signed [17:0] HB;  // sfix18_En14
  wire HB_Valid;
  wire signed [17:0] CIC_COMP;  // sfix18_En14
  wire CIC_COMP_Valid;
  wire signed [17:0] CIC2;  // sfix18_En12
  wire CIC_Valid;
  wire signed [17:0] GC2;  // sfix18_En14
  reg signed [17:0] Delay5_reg [0:5];  // sfix18 [6]
  wire signed [17:0] Delay5_reg_next [0:5];  // sfix18_En14 [6]
  wire signed [17:0] Delay5_out1;  // sfix18_En14
  wire signed [17:0] NCO_out1_re;  // sfix18_En16
  wire signed [17:0] NCO_out1_im;  // sfix18_En16
  wire signed [17:0] Mixer_out1_re;  // sfix18_En16
  wire signed [17:0] Mixer_out1_im;  // sfix18_En16
  reg  [0:5] Delay8_reg;  // ufix1 [6]
  wire [0:5] Delay8_reg_next;  // ufix1 [6]
  wire Delay8_out1;


  Lowpass_Interpolator u_Lowpass_Interpolator (.clk(clk),
                                               .reset(reset),
                                               .enb(clk_enable),
                                               .dataIn(dataIn),  // sfix16_En15
                                               .validIn(ValidIn),
                                               .dataOut(LP),  // sfix18_En14
                                               .validOut(LP_Valid)
                                               );

  Halfband_Interpolator u_Halfband_Interpolator (.clk(clk),
                                                 .reset(reset),
                                                 .enb(clk_enable),
                                                 .dataIn(LP),  // sfix18_En14
                                                 .validIn(LP_Valid),
                                                 .dataOut(HB),  // sfix18_En14
                                                 .validOut(HB_Valid)
                                                 );

  CIC_Compensation_Interpolator u_CIC_Compensation_Interpolator (.clk(clk),
                                                                 .reset(reset),
                                                                 .enb(clk_enable),
                                                                 .dataIn(HB),  // sfix18_En14
                                                                 .validIn(HB_Valid),
                                                                 .dataOut(CIC_COMP),  // sfix18_En14
                                                                 .validOut(CIC_COMP_Valid)
                                                                 );

  // StartHere
  CICInterpolator u_CIC_Interpolator_inst (.clk(clk),
                                           .reset(reset),
                                           .enb(clk_enable),
                                           .dataIn(CIC_COMP),  // sfix18_En14
                                           .validIn(CIC_COMP_Valid),
                                           .dataOut(CIC2),  // sfix18_En12
                                           .validOut(CIC_Valid)
                                           );

  Gain_Correction u_Gain_Correction (.dataIn(CIC2),  // sfix18_En12
                                     .dataOut(GC2)  // sfix18_En14
                                     );

  assign enb = clk_enable;

  always @(posedge clk or posedge reset)
    begin : Delay5_process
      if (reset == 1'b1) begin
        Delay5_reg[0] <= 18'sb000000000000000000;
        Delay5_reg[1] <= 18'sb000000000000000000;
        Delay5_reg[2] <= 18'sb000000000000000000;
        Delay5_reg[3] <= 18'sb000000000000000000;
        Delay5_reg[4] <= 18'sb000000000000000000;
        Delay5_reg[5] <= 18'sb000000000000000000;
      end
      else begin
        if (enb) begin
          Delay5_reg[0] <= Delay5_reg_next[0];
          Delay5_reg[1] <= Delay5_reg_next[1];
          Delay5_reg[2] <= Delay5_reg_next[2];
          Delay5_reg[3] <= Delay5_reg_next[3];
          Delay5_reg[4] <= Delay5_reg_next[4];
          Delay5_reg[5] <= Delay5_reg_next[5];
        end
      end
    end

  assign Delay5_out1 = Delay5_reg[5];
  assign Delay5_reg_next[0] = GC2;
  assign Delay5_reg_next[1] = Delay5_reg[0];
  assign Delay5_reg_next[2] = Delay5_reg[1];
  assign Delay5_reg_next[3] = Delay5_reg[2];
  assign Delay5_reg_next[4] = Delay5_reg[3];
  assign Delay5_reg_next[5] = Delay5_reg[4];



  NCO u_NCO (.clk(clk),
             .reset(reset),
             .enb(clk_enable),
             .validIn(CIC_Valid),
             .complexexp_re(NCO_out1_re),  // sfix18_En16
             .complexexp_im(NCO_out1_im)  // sfix18_En16
             );

  Mixer u_Mixer (.clk(clk),
                 .reset(reset),
                 .enb(clk_enable),
                 .dataIn(Delay5_out1),  // sfix18_En14
                 .ncoIn_re(NCO_out1_re),  // sfix18_En16
                 .ncoIn_im(NCO_out1_im),  // sfix18_En16
                 .mixedOut_re(Mixer_out1_re),  // sfix18_En16
                 .mixedOut_im(Mixer_out1_im)  // sfix18_En16
                 );

  assign Out1_re = Mixer_out1_re;

  assign Out1_im = Mixer_out1_im;

  always @(posedge clk or posedge reset)
    begin : Delay8_process
      if (reset == 1'b1) begin
        Delay8_reg[0] <= 1'b0;
        Delay8_reg[1] <= 1'b0;
        Delay8_reg[2] <= 1'b0;
        Delay8_reg[3] <= 1'b0;
        Delay8_reg[4] <= 1'b0;
        Delay8_reg[5] <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay8_reg[0] <= Delay8_reg_next[0];
          Delay8_reg[1] <= Delay8_reg_next[1];
          Delay8_reg[2] <= Delay8_reg_next[2];
          Delay8_reg[3] <= Delay8_reg_next[3];
          Delay8_reg[4] <= Delay8_reg_next[4];
          Delay8_reg[5] <= Delay8_reg_next[5];
        end
      end
    end

  assign Delay8_out1 = Delay8_reg[5];
  assign Delay8_reg_next[0] = CIC_Valid;
  assign Delay8_reg_next[1] = Delay8_reg[0];
  assign Delay8_reg_next[2] = Delay8_reg[1];
  assign Delay8_reg_next[3] = Delay8_reg[2];
  assign Delay8_reg_next[4] = Delay8_reg[3];
  assign Delay8_reg_next[5] = Delay8_reg[4];



  assign Out2 = Delay8_out1;

  assign ce_out = clk_enable;

endmodule  // HDL_DUC

