cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('DUCforLTEHDL/Constant1','user1');
hilite_system('DUCforLTEHDL/Constant2','user1');
hilite_system('DUCforLTEHDL/Data Type Conversion','user1');
hilite_system('DUCforLTEHDL/HDL_DUC','user1');
hilite_system('DUCforLTEHDL/HDL_DUC/CIC Compensation Interpolator','user1');
hilite_system('DUCforLTEHDL/HDL_DUC/CIC Interpolator','user1');
hilite_system('DUCforLTEHDL/HDL_DUC/Delay5','user1');
hilite_system('DUCforLTEHDL/HDL_DUC/Delay8','user1');
hilite_system('DUCforLTEHDL/HDL_DUC/Gain Correction','user1');
hilite_system('DUCforLTEHDL/HDL_DUC/Gain Correction/Data Type Conversion','user1');
hilite_system('DUCforLTEHDL/HDL_DUC/Gain Correction/<!DOCTYPE HTML PUBLIC "-////W3C////DTD HTML 4.0////EN" "http:////www.w3.org//TR//REC-html40//strict.dtd"> <html><head><meta name="qrichtext" content="1" //><style type="text//css"> p, li { white-space: pre-wrap; } <//style><//head><body align="left" style=" font-family:''Helvetica''; font-size:10px; font-weight:400; font-style:normal;"> <p align="center" style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:10px; font-weight:600;">Divide by 4096<//span><//p> <p align="left" style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:10px;">To right-shift by 12 bits, reinterpret the number to have <//span><//p> <p align="left" style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:10px;">20 fractional bits rather than 8 fractional bits.<//span><//p> <p align="left" style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br //><//p><//body><//html>','user1');
hilite_system('DUCforLTEHDL/HDL_DUC/Halfband Interpolator','user1');
hilite_system('DUCforLTEHDL/HDL_DUC/Lowpass Interpolator','user1');
hilite_system('DUCforLTEHDL/HDL_DUC/Mixer','user1');
hilite_system('DUCforLTEHDL/HDL_DUC/Mixer/Add','user1');
hilite_system('DUCforLTEHDL/HDL_DUC/Mixer/Add1','user1');
hilite_system('DUCforLTEHDL/HDL_DUC/Mixer/Complex to Real-Imag','user1');
hilite_system('DUCforLTEHDL/HDL_DUC/Mixer/Complex to Real-Imag1','user1');
hilite_system('DUCforLTEHDL/HDL_DUC/Mixer/Data Type Conversion1','user1');
hilite_system('DUCforLTEHDL/HDL_DUC/Mixer/Data Type Conversion2','user1');
hilite_system('DUCforLTEHDL/HDL_DUC/Mixer/Delay1','user1');
hilite_system('DUCforLTEHDL/HDL_DUC/Mixer/Delay10','user1');
hilite_system('DUCforLTEHDL/HDL_DUC/Mixer/Delay11','user1');
hilite_system('DUCforLTEHDL/HDL_DUC/Mixer/Delay12','user1');
hilite_system('DUCforLTEHDL/HDL_DUC/Mixer/Delay13','user1');
hilite_system('DUCforLTEHDL/HDL_DUC/Mixer/Delay2','user1');
hilite_system('DUCforLTEHDL/HDL_DUC/Mixer/Delay3','user1');
hilite_system('DUCforLTEHDL/HDL_DUC/Mixer/Delay4','user1');
hilite_system('DUCforLTEHDL/HDL_DUC/Mixer/Delay6','user1');
hilite_system('DUCforLTEHDL/HDL_DUC/Mixer/Delay7','user1');
hilite_system('DUCforLTEHDL/HDL_DUC/Mixer/Product1','user1');
hilite_system('DUCforLTEHDL/HDL_DUC/Mixer/Product2','user1');
hilite_system('DUCforLTEHDL/HDL_DUC/Mixer/Product3','user1');
hilite_system('DUCforLTEHDL/HDL_DUC/Mixer/Product4','user1');
hilite_system('DUCforLTEHDL/HDL_DUC/Mixer/Real-Imag to Complex','user1');
hilite_system('DUCforLTEHDL/HDL_DUC/NCO','user1');
hilite_system('DUCforLTEHDL/Upsample1','user1');
hilite_system('DUCforLTEHDL/Upsample2','user1');
