// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\whdlOFDMTransmitter_up_con\Addressable_Delay_Line_block12.v
// Created: 2023-03-08 15:37:28
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Addressable_Delay_Line_block12
// Source Path: whdlOFDMTransmitter_up_con/OFDM_UC/HDL_DUC/Lowpass Interpolator/whdlOFDMTransmitter_up_con/OFDM_UC/HDL_DUC/Lowpass 
// Interpolator/FIRFilter1/Addressable Delay Lin
// Hierarchy Level: 4
// 
// Addressable Delay Line
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Addressable_Delay_Line_block12
          (clk,
           reset,
           enb_1_32_0,
           dataIn,
           validIn,
           wrAddr,
           rdAddr,
           delayLineEnd,
           dataOut);


  input   clk;
  input   reset;
  input   enb_1_32_0;
  input   signed [15:0] dataIn;  // sfix16_En13
  input   validIn;
  input   [3:0] wrAddr;  // ufix4
  input   [3:0] rdAddr;  // ufix4
  output  signed [15:0] delayLineEnd;  // sfix16_En13
  output  signed [15:0] dataOut;  // sfix16_En13


  reg [3:0] wrAddrREG;  // ufix4
  wire relop_relop1;
  reg  dataEndEn;
  wire wrEnN;
  wire dataEndEnS;
  wire signed [15:0] delayedSignals;  // sfix16_En13
  reg signed [15:0] dataOutReg_reg [0:1];  // sfix16 [2]
  wire signed [15:0] dataOutReg_reg_next [0:1];  // sfix16_En13 [2]
  reg signed [15:0] dataOut_1;  // sfix16_En13


  always @(posedge clk or posedge reset)
    begin : dataOutReg_process
      if (reset == 1'b1) begin
        wrAddrREG <= 4'b0000;
      end
      else begin
        if (enb_1_32_0) begin
          wrAddrREG <= wrAddr;
        end
      end
    end



  assign relop_relop1 = wrAddr != wrAddrREG;



  always @(posedge clk or posedge reset)
    begin : dataOutReg_1_process
      if (reset == 1'b1) begin
        dataEndEn <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          dataEndEn <= relop_relop1;
        end
      end
    end



  assign wrEnN =  ~ dataEndEn;



  assign dataEndEnS = relop_relop1 & wrEnN;



  SimpleDualPortRAM_generic #(.AddrWidth(4),
                              .DataWidth(16)
                              )
                            u_simpleDualPortRam (.clk(clk),
                                                 .enb_1_32_0(enb_1_32_0),
                                                 .wr_din(dataIn),
                                                 .wr_addr(wrAddr),
                                                 .wr_en(validIn),
                                                 .rd_addr(rdAddr),
                                                 .rd_dout(delayedSignals)
                                                 );

  always @(posedge clk or posedge reset)
    begin : dataOutReg_2_process
      if (reset == 1'b1) begin
        dataOutReg_reg[0] <= 16'sb0000000000000000;
        dataOutReg_reg[1] <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_32_0 && dataEndEnS) begin
          dataOutReg_reg[0] <= dataOutReg_reg_next[0];
          dataOutReg_reg[1] <= dataOutReg_reg_next[1];
        end
      end
    end

  assign delayLineEnd = dataOutReg_reg[1];
  assign dataOutReg_reg_next[0] = delayedSignals;
  assign dataOutReg_reg_next[1] = dataOutReg_reg[0];



  always @(posedge clk or posedge reset)
    begin : reg_rsvd_process
      if (reset == 1'b1) begin
        dataOut_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_32_0) begin
          dataOut_1 <= delayedSignals;
        end
      end
    end



  assign dataOut = dataOut_1;

endmodule  // Addressable_Delay_Line_block12

