// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\whdlOFDMTransmitter_up_con\castSection.v
// Created: 2023-03-08 15:37:28
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: castSection
// Source Path: whdlOFDMTransmitter_up_con/OFDM_UC/HDL_DUC/CICInterpolator/castSection
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module castSection
          (gcOut_re,
           gcOut_im,
           dataOut_re,
           dataOut_im);


  input   signed [19:0] gcOut_re;  // sfix20_En14
  input   signed [19:0] gcOut_im;  // sfix20_En14
  output  signed [17:0] dataOut_re;  // sfix18_En12
  output  signed [17:0] dataOut_im;  // sfix18_En12




  assign dataOut_re = gcOut_re[19:2];



  assign dataOut_im = gcOut_im[19:2];



endmodule  // castSection

