// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\whdlOFDMTransmitter_up_con\FilterTapSystolicPreAdd_block4.v
// Created: 2023-02-23 11:56:52
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FilterTapSystolicPreAdd_block4
// Source Path: whdlOFDMTransmitter_up_con/OFDM_UC/HDL_DUC/Lowpass Interpolator/whdlOFDMTransmitter_up_con/OFDM_UC/HDL_DUC/Lowpass 
// Interpolator/FIRFilter1/FilterTapSystolicPreAd
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FilterTapSystolicPreAdd_block4
          (clk,
           enb_1_32_0,
           din_im,
           preAddIn,
           coeff,
           sumIn,
           sumOut);


  input   clk;
  input   enb_1_32_0;
  input   signed [15:0] din_im;  // sfix16_En13
  input   signed [15:0] preAddIn;  // sfix16_En13
  input   signed [15:0] coeff;  // sfix16_En15
  input   signed [31:0] sumIn;  // sfix32_En28
  output  signed [31:0] sumOut;  // sfix32_En28


  reg signed [15:0] fTap_din1_reg1;  // sfix16
  reg signed [15:0] fTap_din1_reg2;  // sfix16
  reg signed [15:0] fTap_din2_reg1;  // sfix16
  reg signed [16:0] fTap_preAdd_reg;  // sfix17
  reg signed [32:0] fTap_mult_reg;  // sfix33
  reg signed [31:0] fTap_addout_reg;  // sfix32
  reg signed [15:0] fTap_coef_reg1;  // sfix16
  reg signed [15:0] fTap_coef_reg2;  // sfix16
  wire signed [16:0] fTap_preAdd_reg_next;  // sfix17_En13
  wire signed [32:0] fTap_mult_reg_next;  // sfix33_En28
  wire signed [31:0] fTap_addout_reg_next;  // sfix32_En28
  wire signed [31:0] fTap_add_cast;  // sfix32_En28
  wire signed [16:0] fTap_add_cast_1;  // sfix17_En13
  wire signed [16:0] fTap_add_cast_2;  // sfix17_En13

  initial begin
    fTap_din1_reg1 = 16'sb0000000000000000;
    fTap_din1_reg2 = 16'sb0000000000000000;
    fTap_din2_reg1 = 16'sb0000000000000000;
    fTap_preAdd_reg = 17'sb00000000000000000;
    fTap_coef_reg1 = 16'sb0000000000000000;
    fTap_coef_reg2 = 16'sb0000000000000000;
    fTap_mult_reg = 33'sh000000000;
    fTap_addout_reg = 32'sb00000000000000000000000000000000;
  end

  // FilterTapSystolicPreAddS
  always @(posedge clk)
    begin : fTap_process
      if (enb_1_32_0) begin
        fTap_preAdd_reg <= fTap_preAdd_reg_next;
        fTap_mult_reg <= fTap_mult_reg_next;
        fTap_addout_reg <= fTap_addout_reg_next;
        fTap_din1_reg2 <= fTap_din1_reg1;
        fTap_din1_reg1 <= din_im;
        fTap_din2_reg1 <= preAddIn;
        fTap_coef_reg2 <= fTap_coef_reg1;
        fTap_coef_reg1 <= coeff;
      end
    end

  assign sumOut = fTap_addout_reg;
  assign fTap_add_cast = fTap_mult_reg[31:0];
  assign fTap_addout_reg_next = fTap_add_cast + sumIn;
  assign fTap_mult_reg_next = fTap_preAdd_reg * fTap_coef_reg2;
  assign fTap_add_cast_1 = {fTap_din1_reg2[15], fTap_din1_reg2};
  assign fTap_add_cast_2 = {fTap_din2_reg1[15], fTap_din2_reg1};
  assign fTap_preAdd_reg_next = fTap_add_cast_1 + fTap_add_cast_2;



endmodule  // FilterTapSystolicPreAdd_block4

