// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\whdlOFDMTransmitter_up_con\gcSection.v
// Created: 2023-03-08 15:37:28
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: gcSection
// Source Path: whdlOFDMTransmitter_up_con/OFDM_UC/HDL_DUC/CICInterpolator/gcSection
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module gcSection
          (integOut_re,
           integOut_im,
           gcOut_re,
           gcOut_im);


  input   signed [19:0] integOut_re;  // sfix20_En14
  input   signed [19:0] integOut_im;  // sfix20_En14
  output  signed [19:0] gcOut_re;  // sfix20_En14
  output  signed [19:0] gcOut_im;  // sfix20_En14




  assign gcOut_re = integOut_re;

  assign gcOut_im = integOut_im;

endmodule  // gcSection

