// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\whdlOFDMTransmitter_up_con\OFDM_Transmitter.v
// Created: 2023-03-08 15:37:28
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: OFDM_Transmitter
// Source Path: whdlOFDMTransmitter_up_con/OFDM_UC/OFDM Transmitter
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module OFDM_Transmitter
          (clk,
           reset,
           enb_1_32_0,
           enb,
           enb_1_2_0,
           enb_1_32_1,
           modTypeIndex,
           codeRateIndex,
           data,
           valid,
           txData_re,
           txData_im,
           txValid,
           ready);


  input   clk;
  input   reset;
  input   enb_1_32_0;
  input   enb;
  input   enb_1_2_0;
  input   enb_1_32_1;
  input   [1:0] modTypeIndex;  // ufix2
  input   [1:0] codeRateIndex;  // ufix2
  input   data;
  input   valid;
  output  signed [15:0] txData_re;  // sfix16_En13
  output  signed [15:0] txData_im;  // sfix16_En13
  output  txValid;
  output  ready;


  wire signed [15:0] whdlOFDMTx_Model_out1_re;  // sfix16_En13
  wire signed [15:0] whdlOFDMTx_Model_out1_im;  // sfix16_En13
  wire whdlOFDMTx_Model_out2;
  wire whdlOFDMTx_Model_out3;


  whdlOFDMTx_whdlOFDMTx u_whdlOFDMTx_Model (.clk(clk),
                                            .reset(reset),
                                            .enb_1_32_0(enb_1_32_0),
                                            .enb(enb),
                                            .enb_1_2_0(enb_1_2_0),
                                            .enb_1_32_1(enb_1_32_1),
                                            .modTypeIndex(modTypeIndex),  // ufix2
                                            .codeRateIndex(codeRateIndex),  // ufix2
                                            .data(data),
                                            .valid(valid),
                                            .txData_re(whdlOFDMTx_Model_out1_re),  // sfix16_En13
                                            .txData_im(whdlOFDMTx_Model_out1_im),  // sfix16_En13
                                            .txValid(whdlOFDMTx_Model_out2),
                                            .ready(whdlOFDMTx_Model_out3)
                                            );

  assign txData_re = whdlOFDMTx_Model_out1_re;

  assign txData_im = whdlOFDMTx_Model_out1_im;

  assign txValid = whdlOFDMTx_Model_out2;

  assign ready = whdlOFDMTx_Model_out3;

endmodule  // OFDM_Transmitter

