webtalk_init -webtalk_dir D:/Vivado_projects/OFDM_UC/OFDM_UC.sim/sim_1/behav/xsim/xsim.dir/OFDM_UC_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Feb 23 15:35:50 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ecd725f2-2f81-48ff-8178-eb56afa8212c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "14fa89fdb7d54d478d0fa3f580346094" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 4600H with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2994 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "5453090 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "115.14_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "25452_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3231361116 -regid "" -xml D:/Vivado_projects/OFDM_UC/OFDM_UC.sim/sim_1/behav/xsim/xsim.dir/OFDM_UC_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Vivado_projects/OFDM_UC/OFDM_UC.sim/sim_1/behav/xsim/xsim.dir/OFDM_UC_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Vivado_projects/OFDM_UC/OFDM_UC.sim/sim_1/behav/xsim/xsim.dir/OFDM_UC_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
