# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Digital Design/Graduation_Project/Projects/whdlOFDMTransmitter_up_con/zedboard.xdc

# XDC: D:/Digital Design/Graduation_Project/Projects/whdlOFDMTransmitter_up_con/Gynesys.xdc

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
