# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Vivado_projects/OFDM_UC/OFDM_UC.cache/wt [current_project]
set_property parent.project_path D:/Vivado_projects/OFDM_UC/OFDM_UC.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zedboard:part0:1.0 [current_project]
set_property ip_output_repo d:/Vivado_projects/OFDM_UC/OFDM_UC.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/Addressable_Delay_Line.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/Addressable_Delay_Line_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/Addressable_Delay_Line_block1.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/Addressable_Delay_Line_block10.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/Addressable_Delay_Line_block11.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/Addressable_Delay_Line_block12.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/Addressable_Delay_Line_block13.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/Addressable_Delay_Line_block14.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/Addressable_Delay_Line_block15.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/Addressable_Delay_Line_block16.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/Addressable_Delay_Line_block17.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/Addressable_Delay_Line_block18.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/Addressable_Delay_Line_block2.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/Addressable_Delay_Line_block3.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/Addressable_Delay_Line_block4.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/Addressable_Delay_Line_block5.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/Addressable_Delay_Line_block6.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/Addressable_Delay_Line_block7.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/Addressable_Delay_Line_block8.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/Addressable_Delay_Line_block9.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/CICInterpolator.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/CIC_Compensation_Interpolator.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/DitherGen.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/FIRFilter1.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/FIRFilter1_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/FIRFilter1_block1.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/FIRFilter2.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/FIRFilter2_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/FIRFilter2_block1.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/FilterTapSystolic.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/FilterTapSystolicPreAdd.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/FilterTapSystolicPreAdd_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/FilterTapSystolicPreAdd_block1.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/FilterTapSystolicPreAdd_block2.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/FilterTapSystolic_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/FilterTapSystolic_block1.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/FilterTapSystolic_block2.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/FilterTapSystolic_block3.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/FilterTapSystolic_block4.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/FirRdyLogic.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/FirRdyLogic_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/FirRdyLogic_block1.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/FirRdyLogic_block2.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/FirRdyLogic_block3.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/FirRdyLogic_block4.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/Gain_Correction.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/HDL_DUC.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/Halfband_Interpolator.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/LookUpTableGen.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/Lowpass_Interpolator.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/Mixer.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/NCO.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/OFDM_Transmitter.v}
  {D:/Digital Design/Graduation_Project/Projects/whdlOFDMTransmitter_up_con/OFDM_UC.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/OFDM_UC_tc.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/SimpleDualPortRAM_generic.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/WaveformGen.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/cSection.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/castSection.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/gcSection.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/iSection.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/rdySection.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/usSection.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_CPAddition.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_CRCGenCompute.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_CRCGenCompute_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_CRCGenControl.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_CRCGenControl_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Complex4Multiply.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Complex4Multiply_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Complex4Multiply_block1.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Control_OFDM_Signal_Generation.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Convolutional_Encoder.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Convolutional_Encoder_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Counter_for_Read_Address.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Create_Control_Bus.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Create_Control_Bus_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Data.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Data_Chain.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Data_and_Control_Signal_Generation.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Disable_OFDM_Generation.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Discrete_FIR_Filter.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_DualRateDualPortRAM_generic.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Enable_Header_and_Preamble.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Falling_Edge_Detector.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Falling_Edge_Detector1.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Falling_Edge_Detector2.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Filter.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_FilterCoef.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_FilterTapSystolicPreAddWvlIn.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Frame_Controller.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Frame_Controller_and_Input_Sampler.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Frame_Formation_and_OFDM_Modulation.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Frame_Generator.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_General_CRC_Generator_HDL_Optimized.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_General_CRC_Generator_HDL_Optimized_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Generate_Base_Read_Address.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Generate_Base_Read_Address_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Generate_Current_Frame_Status.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Generate_Current_Frame_Status_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Generate_Forced_End.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Generate_Forced_End_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Generate_OFDM_Modulator_Ready.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Generate_OFDM_Modulator_Valid.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Generate_Output_Control_Signals.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Generate_Output_Control_Signals_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Generate_Preamble_Control_Signals.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Generate_RAM_Inputs.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Generate_Read_Address.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Generate_Read_Address_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Generate_Ready.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Generate_Ready2.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Generate_Ready2_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Generate_Ready_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Generate_Transmitter_Ready.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Generate_Write_Address.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Generate_Write_Address_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_HDLFFTShiftMod.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Handle_Input_Control_Signals.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Handle_Input_Control_Signals_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Header.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Header_Formation.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Input_Sampler.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Interleaver.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Interleaver_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_LTE_Symbol_Modulator.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_LTE_Symbol_Modulator_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_MATLAB_Function.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_MATLAB_Function1.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_MATLAB_Function1_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_MATLAB_Function1_block1.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_MATLAB_Function2.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_MATLAB_Function3.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_MATLAB_Function4.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_MATLAB_Function5.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_MATLAB_Function_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Make_OFDM_Valid_Continuous.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Multiplex_Header_and_Data_Signals.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Multiplex_Preamble_Signals.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Multiplexer.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_OFDM_Modulator.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Pilot.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Priority_Encoder.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Pulse_Generator.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Puncturer.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_RADIX22FFT_CTRL1_1.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_RADIX22FFT_CTRL1_1_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_RADIX22FFT_CTRL1_2.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_RADIX22FFT_CTRL1_3.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_RADIX22FFT_CTRL1_4.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_RADIX22FFT_CTRL1_5.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_RADIX22FFT_CTRL1_6.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_RADIX22FFT_SDF1_1.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_RADIX22FFT_SDF1_3.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_RADIX22FFT_SDF1_5.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_RADIX22FFT_SDF1_7.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_RADIX22FFT_SDF2_2.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_RADIX22FFT_SDF2_4.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_RADIX22FFT_SDF2_6.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_RADIX2FFT_bitNatural.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Random_OFDM_Symbol.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Read_Logic.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Read_Logic_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Reference_Signals.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Rising_Edge_Detector.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Rising_Edge_Detector_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_SDFCommutator1.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_SDFCommutator2.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_SDFCommutator3.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_SDFCommutator4.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_SDFCommutator5.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_SDFCommutator6.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_SDFCommutator7.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Sample_Control_Bus_Creator.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Sample_Control_Bus_Creator_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Scrambler.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Select_Puncture_Vector.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Serialize_Start_and_End_Signals.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Serializer.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_SimpleDualPortRAM_generic.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_SimpleDualPortRAM_generic_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_SimpleDualPortRAM_generic_block1.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_SimpleDualPortRAM_singlebit.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_SimpleDualPortRAM_singlebit_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Split_Data_Into_Symbols.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Store_Block_Lengths.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Store_Block_Lengths_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Symbol_Interleaver.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Synchronization_Sequence.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_TWDLROM_3_1.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_TWDLROM_5_1.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_TWDLROM_7_1.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Write_Logic.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_Write_Logic_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_controlUnit.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_controlUnit_block.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_dsphdl_IFFT.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_subFilter.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_symbolFormation.v}
  {D:/Digital Design/Graduation_Project/Projects/OFDM_last/whdlOFDMTransmitter_up_con/whdlOFDMTx/whdlOFDMTx_whdlOFDMTx.v}
  {D:/Digital Design/Graduation_Project/Projects/whdlOFDMTransmitter_up_con/DUC_DAC.v}
}
read_ip -quiet D:/Vivado_projects/OFDM_UC/OFDM_UC.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/Vivado_projects/OFDM_UC/OFDM_UC.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado_projects/OFDM_UC/OFDM_UC.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado_projects/OFDM_UC/OFDM_UC.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/Digital Design/Graduation_Project/Projects/whdlOFDMTransmitter_up_con/zedboard.xdc}}
set_property used_in_implementation false [get_files {{D:/Digital Design/Graduation_Project/Projects/whdlOFDMTransmitter_up_con/zedboard.xdc}}]

read_xdc {{D:/Digital Design/Graduation_Project/Projects/whdlOFDMTransmitter_up_con/Gynesys.xdc}}
set_property used_in_implementation false [get_files {{D:/Digital Design/Graduation_Project/Projects/whdlOFDMTransmitter_up_con/Gynesys.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top DUC_DAC -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef DUC_DAC.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file DUC_DAC_utilization_synth.rpt -pb DUC_DAC_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
